# Generated by Django 6.0.6 on 2026-06-14 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sistema', 'Sistema'), ('corredor', 'Corredor'), ('gerente', 'Gerente'), ('superadmin', 'Superadmin'), ('usuario_base', 'Usuario Base')], max_length=50, verbose_name='Tipo de comunicación')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('property_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID propiedad')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID objeto relacionado')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leído')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('emitter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Emisor')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
            ],
            options={
                'verbose_name': 'Comunicación',
                'verbose_name_plural': 'Comunicaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
