# Generated by Django 6.0.6 on 2026-08-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a01Com', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='related_object_type',
            field=models.CharField(blank=True, default='', help_text="'servicio' apunta al detalle de revisión de servicio; vacío/solicitud apunta al detalle de solicitud de propiedad.", max_length=20, verbose_name='Tipo de objeto relacionado'),
        ),
    ]
