# Generated by Django 6.0.6 on 2026-09-01 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a01Com', '0002_communication_related_object_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email del consultante')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono / Celular')),
                ('mensaje', models.TextField(verbose_name='Mensaje de consulta')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('respondida', 'Respondida'), ('cerrada', 'Cerrada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('respuesta', models.TextField(blank=True, verbose_name='Respuesta enviada')),
                ('respondido_at', models.DateTimeField(blank=True, null=True, verbose_name='Respondido el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_contacto_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Consulta de contacto',
                'verbose_name_plural': 'Consultas de contacto',
                'ordering': ['-created_at'],
            },
        ),
    ]
