# Generated by Django 6.0.6 on 2026-10-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a01Com', '0004_backfill_postulacion_related_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='related_object_type',
            field=models.CharField(blank=True, default='', help_text="'servicio' apunta al detalle de revisión de servicio; 'consulta' al detalle de consulta; 'postulacion' al detalle de postulación a corredor; vacío/solicitud apunta al detalle de solicitud de propiedad.", max_length=20, verbose_name='Tipo de objeto relacionado'),
        ),
    ]
