# Generated by Django 6.0.6 on 2026-06-18 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a00seg', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPagoPubli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_nombre', models.CharField(max_length=120, verbose_name='Nombre del banco')),
                ('tipo_cuenta', models.CharField(choices=[('vista', 'Cuenta Vista'), ('corriente', 'Cuenta Corriente'), ('vale_vista', 'Vale Vista'), ('otras', 'Otras')], max_length=20, verbose_name='Tipo de cuenta')),
                ('numero_cuenta', models.CharField(max_length=50, verbose_name='Número de cuenta')),
                ('dni_titular', models.CharField(max_length=20, verbose_name='RUT')),
                ('titular', models.CharField(max_length=255, verbose_name='Titular')),
                ('email_confirmacion', models.EmailField(max_length=254, verbose_name='Correo de confirmación')),
                ('valor_pub_venta_mensual', models.PositiveIntegerField(default=4000, verbose_name='Valor publicación venta x mes')),
                ('valor_destacado_venta_mensual', models.PositiveIntegerField(default=6000, verbose_name='Valor destacado venta x mes')),
                ('valor_pub_arriendo_mensual', models.PositiveIntegerField(default=5000, verbose_name='Valor arriendo mensual')),
                ('valor_destacado_arriendo_mensual', models.PositiveIntegerField(default=3000, verbose_name='Valor arriendo destacado mensual')),
                ('valor_pub_str_dia', models.PositiveIntegerField(default=5000, verbose_name='Valor SRT x día')),
                ('valor_destacado_str_dia', models.PositiveIntegerField(default=3000, verbose_name='Valor SRT destacado x día')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Configuración de pago de publicación',
                'verbose_name_plural': 'Configuraciones de pago de publicaciones',
            },
        ),
        migrations.CreateModel(
            name='ServiciosProp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del servicio')),
                ('icono', models.CharField(blank=True, max_length=50, verbose_name='Icono (clase CSS/emoji)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Servicio de propiedad',
                'verbose_name_plural': 'Servicios de propiedades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=255, verbose_name='Calle / Dirección')),
                ('numero_calle', models.CharField(max_length=20, verbose_name='Número')),
                ('tipo_prop', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('local', 'Local Comercial'), ('terreno', 'Terreno'), ('oficina', 'Oficina'), ('bodega', 'Bodega'), ('parcela', 'Parcela'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de propiedad')),
                ('num_tipo_prop', models.CharField(blank=True, max_length=50, verbose_name='Número / Identificación (Dpto, Lote, etc.)')),
                ('poblacion_localidad', models.CharField(blank=True, max_length=255, verbose_name='Población / Localidad')),
                ('numero_dormitorios', models.PositiveSmallIntegerField(default=0, verbose_name='N° Dormitorios')),
                ('numero_banos', models.PositiveSmallIntegerField(default=0, verbose_name='N° Baños')),
                ('descripcion_propiedad', models.TextField(blank=True, verbose_name='Descripción de la propiedad')),
                ('descripcion_entorno', models.TextField(blank=True, verbose_name='Descripción del entorno')),
                ('tipo_uso', models.CharField(choices=[('habitacional', 'Habitacional'), ('comercial', 'Comercial'), ('agro', 'Agrícola')], default='habitacional', max_length=20, verbose_name='Tipo de uso')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('archivada', 'Archivada')], default='borrador', max_length=20, verbose_name='Estado')),
                ('tipo_accion', models.CharField(choices=[('venta', 'Venta'), ('arriendo', 'Arriendo'), ('srt', 'Short Rental Time (SRT)')], max_length=20, verbose_name='Tipo de acción')),
                ('tipo_moneda', models.CharField(choices=[('PCL', 'Pesos Chilenos (CLP)'), ('UF', 'UF'), ('USD', 'USD')], default='PCL', max_length=5, verbose_name='Tipo de moneda')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio')),
                ('m_construidos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='M² construidos')),
                ('m_terreno', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='M² terreno')),
                ('num_estacionamientos', models.PositiveSmallIntegerField(default=0, verbose_name='N° Estacionamientos')),
                ('montomensual_gastoscomunes_pcl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gastos comunes mensuales (CLP)')),
                ('montoanual_contribuciones_pcl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Contribuciones anuales (CLP)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a00seg.comuna', verbose_name='Comuna')),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to=settings.AUTH_USER_MODEL, verbose_name='Dueño')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a00seg.region', verbose_name='Región')),
                ('servicios_prop', models.ManyToManyField(blank=True, to='a03Prop.serviciosprop', verbose_name='Servicios / Características')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocsUsu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del documento')),
                ('documento', models.FileField(upload_to='docs_legales_usu/', verbose_name='Documento')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Subido el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs_usuarios', to='a03Prop.propiedad', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Documento legal de usuario',
                'verbose_name_plural': 'Documentos legales de usuarios',
            },
        ),
        migrations.CreateModel(
            name='LegalDocsProp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del documento')),
                ('documento', models.FileField(upload_to='docs_legales_prop/', verbose_name='Documento')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Subido el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs_legales', to='a03Prop.propiedad', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Documento legal de propiedad',
                'verbose_name_plural': 'Documentos legales de propiedades',
            },
        ),
        migrations.CreateModel(
            name='FotosPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='propiedades/', verbose_name='Imagen')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='a03Prop.propiedad', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Foto de propiedad',
                'verbose_name_plural': 'Fotos de propiedades',
            },
        ),
        migrations.CreateModel(
            name='CorredorProp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comision', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('fijo', 'Monto Fijo')], default='porcentaje', max_length=20, verbose_name='Tipo de comisión')),
                ('monto_comision_usu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Comisión (usuario)')),
                ('monto_comision_dueno', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Comisión (dueño)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'Activa'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('corredor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Corredor')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corredores', to='a03Prop.propiedad', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Corredor de propiedad',
                'verbose_name_plural': 'Corredores de propiedades',
            },
        ),
        migrations.CreateModel(
            name='PublicacionProp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meses', models.PositiveIntegerField(default=1, verbose_name='Meses de publicación')),
                ('es_destacada', models.BooleanField(default=False, verbose_name='¿Es destacada?')),
                ('total_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total pagado')),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante de pago')),
                ('inicia_at', models.DateTimeField(blank=True, null=True, verbose_name='Inicia el')),
                ('expira_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira el')),
                ('estado', models.CharField(choices=[('no_iniciada', 'No iniciada'), ('en_revision', 'En revisión'), ('objetada', 'Objetada'), ('publicada', 'Publicada'), ('renovada', 'Renovada'), ('archivada', 'Archivada')], default='no_iniciada', max_length=20, verbose_name='Estado')),
                ('renovacion_avisada', models.BooleanField(default=False, verbose_name='Renovación avisada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='a03Prop.propiedad', verbose_name='Propiedad')),
                ('publicante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to=settings.AUTH_USER_MODEL, verbose_name='Publicante')),
            ],
            options={
                'verbose_name': 'Publicación de propiedad',
                'verbose_name_plural': 'Publicaciones de propiedades',
            },
        ),
        migrations.CreateModel(
            name='SolicitudPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meses', models.PositiveIntegerField(default=1, verbose_name='Meses de publicación')),
                ('es_destacada', models.BooleanField(default=False, verbose_name='¿Destacada?')),
                ('total_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total a pagar')),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes_solicitud/', verbose_name='Comprobante de pago')),
                ('orden_gestion', models.FileField(blank=True, null=True, upload_to='ordenes_gestion/', verbose_name='Orden de Gestión (PDF)')),
                ('og_aceptada', models.BooleanField(default=False, verbose_name='Orden de Gestión aceptada')),
                ('og_aceptada_at', models.DateTimeField(blank=True, null=True, verbose_name='Aceptada el')),
                ('docs_requeridos', models.TextField(blank=True, help_text='Lista de documentos que el usuario debe subir (separados por coma)', verbose_name='Documentos requeridos')),
                ('estado', models.CharField(choices=[('pago_revision', 'Pago en revisión'), ('pago_objetado', 'Pago objetado'), ('pago_aprobado', 'Pago aprobado'), ('esperando_corredor', 'Esperando asignación de corredor'), ('en_revision_corredor', 'En revisión del corredor'), ('og_pendiente', 'Orden de Gestión pendiente de aceptación'), ('en_validacion', 'En validación final'), ('publicada', 'Publicada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pago_revision', max_length=30, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('corredor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_publicacion_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Corredor asignado')),
                ('propiedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='a03Prop.propiedad', verbose_name='Propiedad asociada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_publicacion', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud de publicación',
                'verbose_name_plural': 'Solicitudes de publicación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObservacionSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Observación')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='obs_solicitud/', verbose_name='Archivo adjunto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='a03Prop.solicitudpublicacion', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Observación de solicitud',
                'verbose_name_plural': 'Observaciones de solicitudes',
                'ordering': ['created_at'],
            },
        ),
    ]
