# Generated by Django 6.0.6 on 2026-06-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a03Prop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='tiene_bodega',
            field=models.BooleanField(default=False, verbose_name='¿Tiene bodega?'),
        ),
    ]
