# Generated by Django 6.0.6 on 2026-06-21 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a03Prop', '0002_propiedad_tiene_bodega'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritaProp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Agregada el')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritada_por', to='a03Prop.propiedad', verbose_name='Propiedad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Favorita',
                'verbose_name_plural': 'Favoritas',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'propiedad'), name='unique_favorita_usuario_propiedad')],
            },
        ),
    ]
