# Generated by Django 6.0.6 on 2026-06-23 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a00seg', '0002_agendacorredor_reservado'),
        ('a03Prop', '0003_favoritaprop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitada', models.DateField(verbose_name='Fecha solicitada')),
                ('hora_inicio_solicitada', models.TimeField(verbose_name='Hora inicio solicitada')),
                ('hora_fin_solicitada', models.TimeField(verbose_name='Hora fin solicitada')),
                ('fecha_reprogramada', models.DateField(blank=True, null=True, verbose_name='Fecha reprogramada')),
                ('hora_reprogramada_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora reprogramada inicio')),
                ('hora_reprogramada_fin', models.TimeField(blank=True, null=True, verbose_name='Hora reprogramada fin')),
                ('mensaje_reprogramacion', models.TextField(blank=True, verbose_name='Mensaje de reprogramación')),
                ('orden_visita', models.FileField(blank=True, null=True, upload_to='ordenes_visita/', verbose_name='Orden de Visita (PDF)')),
                ('clausulas_aceptadas', models.BooleanField(default=False, verbose_name='Cláusulas de OV aceptadas')),
                ('clausulas_aceptadas_at', models.DateTimeField(blank=True, null=True, verbose_name='Aceptadas el')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de confirmación'), ('aceptada', 'Aceptada por el corredor'), ('rechazada', 'Rechazada'), ('reprogramada', 'Reprogramada (propuesta de nueva fecha)'), ('realizada', 'Visita realizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('realizada_at', models.DateTimeField(blank=True, null=True, verbose_name='Realizada el')),
                ('bloque_agenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_solicitadas', to='a00seg.agendacorredor', verbose_name='Bloque de agenda seleccionado')),
                ('corredor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Corredor responsable')),
                ('orden_visita_subida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_visita_subidas', to=settings.AUTH_USER_MODEL, verbose_name='Subida por')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_visita', to='a03Prop.propiedad', verbose_name='Propiedad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_visita', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud de visita',
                'verbose_name_plural': 'Solicitudes de visitas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropuestaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compra', 'Propuesta de Compra'), ('arriendo', 'Propuesta de Arriendo')], max_length=20, verbose_name='Tipo de propuesta')),
                ('monto_ofrecido', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto ofrecido')),
                ('moneda', models.CharField(choices=[('PCL', 'Pesos Chilenos (CLP)'), ('UF', 'UF'), ('USD', 'USD')], default='PCL', max_length=5, verbose_name='Moneda')),
                ('condiciones', models.TextField(blank=True, verbose_name='Condiciones / Detalles')),
                ('nombre_comprador', models.CharField(max_length=255, verbose_name='Nombre del oferente')),
                ('rut_comprador', models.CharField(max_length=20, verbose_name='RUT/DNI del oferente')),
                ('email_comprador', models.EmailField(max_length=254, verbose_name='Email del oferente')),
                ('telefono_comprador', models.CharField(max_length=20, verbose_name='Teléfono del oferente')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('contra_oferta', 'Contraoferta')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('solicitud_visita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='propuesta', to='a03Prop.solicitudvisita', verbose_name='Solicitud de visita')),
            ],
            options={
                'verbose_name': 'Propuesta',
                'verbose_name_plural': 'Propuestas',
                'ordering': ['-created_at'],
            },
        ),
    ]
