# Generated by Django 6.0.6 on 2026-06-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a03Prop', '0004_solicitudvisita_propuestacompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvisita',
            name='motivo_rechazo',
            field=models.TextField(blank=True, verbose_name='Motivo del rechazo'),
        ),
    ]
