# Generated by Django 6.0.6 on 2026-06-26 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a03Prop', '0006_solicitudvisita_campos_arriendo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvisita',
            name='pausado',
            field=models.BooleanField(default=False, verbose_name='Pausado por proceso de compra activo'),
        ),
        migrations.CreateModel(
            name='ProcesoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('propuesta_aceptada', 'Propuesta aceptada — Pendiente de Promesa de Compraventa'), ('promesa_observacion', 'Promesa de Compraventa — En observaciones'), ('promesa_aceptada', 'Promesa de Compraventa — Aceptada por ambas partes'), ('instrucciones_observacion', 'Instrucciones Notariales — En observaciones'), ('instrucciones_aceptada', 'Instrucciones Notariales — Aceptadas por ambas partes'), ('contrato_pendiente', 'Pendiente de subir Contrato de Compraventa'), ('contrato_listo', 'Contrato de Compraventa listo — Pendiente de firma notarial'), ('firma_notarial', 'Firma notarial realizada'), ('escritura_cbr', 'Escritura en inscripción en CBR'), ('escritura_aprobada', 'Escritura inscrita — Operación finalizada'), ('escritura_rechazada', 'Inscripción rechazada — Requiere gestión'), ('cancelado', 'Proceso cancelado — Comprador no cumplió'), ('finalizado', 'Proceso completado exitosamente')], default='propuesta_aceptada', max_length=30, verbose_name='Estado')),
                ('promesa_documento', models.FileField(blank=True, null=True, upload_to='promesas_compraventa/', verbose_name='Documento de Promesa de Compraventa')),
                ('promesa_ronda', models.PositiveIntegerField(default=0, verbose_name='Ronda de observaciones (Promesa)')),
                ('promesa_aceptado_vendedor', models.BooleanField(default=False, verbose_name='Vendedor aceptó Promesa')),
                ('promesa_aceptado_vendedor_at', models.DateTimeField(blank=True, null=True)),
                ('promesa_aceptado_comprador', models.BooleanField(default=False, verbose_name='Comprador aceptó Promesa')),
                ('promesa_aceptado_comprador_at', models.DateTimeField(blank=True, null=True)),
                ('promesa_aceptado_at', models.DateTimeField(blank=True, null=True, verbose_name='Aceptada por ambos el')),
                ('instrucciones_documento', models.FileField(blank=True, null=True, upload_to='instrucciones_notariales/', verbose_name='Documento de Instrucciones Notariales')),
                ('instrucciones_ronda', models.PositiveIntegerField(default=0, verbose_name='Ronda de observaciones (Instrucciones)')),
                ('instrucciones_aceptado_vendedor', models.BooleanField(default=False)),
                ('instrucciones_aceptado_vendedor_at', models.DateTimeField(blank=True, null=True)),
                ('instrucciones_aceptado_comprador', models.BooleanField(default=False)),
                ('instrucciones_aceptado_comprador_at', models.DateTimeField(blank=True, null=True)),
                ('instrucciones_aceptado_at', models.DateTimeField(blank=True, null=True)),
                ('contrato_documento', models.FileField(blank=True, null=True, upload_to='contratos_compraventa/', verbose_name='Documento de Contrato de Compraventa')),
                ('contrato_firmado', models.BooleanField(default=False)),
                ('contrato_firmado_at', models.DateTimeField(blank=True, null=True)),
                ('notaria_nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre de la notaría')),
                ('notaria_direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección de la notaría')),
                ('notaria_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de firma notarial')),
                ('notaria_hora', models.TimeField(blank=True, null=True, verbose_name='Hora de firma notarial')),
                ('escritura_ingresada_at', models.DateTimeField(blank=True, null=True, verbose_name='Ingresada a CBR el')),
                ('escritura_resultado', models.CharField(blank=True, choices=[('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], max_length=20, null=True, verbose_name='Resultado de inscripción')),
                ('escritura_resultado_at', models.DateTimeField(blank=True, null=True)),
                ('escritura_comunicado', models.BooleanField(default=False, verbose_name='Resultado comunicado a las partes')),
                ('escritura_comunicado_at', models.DateTimeField(blank=True, null=True)),
                ('otros_pausados', models.BooleanField(default=False, verbose_name='Otros procesos pausados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('completado_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado el')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL, verbose_name='Comprador')),
                ('contrato_subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Contrato subido por')),
                ('corredor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_compra', to=settings.AUTH_USER_MODEL, verbose_name='Corredor responsable')),
                ('instrucciones_subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrucciones_subidas', to=settings.AUTH_USER_MODEL, verbose_name='Instrucciones subidas por')),
                ('promesa_subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promesas_subidas', to=settings.AUTH_USER_MODEL, verbose_name='Promesa subida por')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_compra', to='a03Prop.propiedad', verbose_name='Propiedad')),
                ('propuesta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proceso', to='a03Prop.propuestacompra', verbose_name='Propuesta')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor (Dueño)')),
            ],
            options={
                'verbose_name': 'Proceso de Compra',
                'verbose_name_plural': 'Procesos de Compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObservacionProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('promesa', 'Promesa de Compraventa'), ('instrucciones', 'Instrucciones Notariales'), ('contrato', 'Contrato de Compraventa')], max_length=20, verbose_name='Etapa')),
                ('ronda', models.PositiveIntegerField(default=1, verbose_name='N° de ronda')),
                ('texto', models.TextField(verbose_name='Observación')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='obs_proceso/', verbose_name='Archivo adjunto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='a03Prop.procesocompra', verbose_name='Proceso')),
            ],
            options={
                'verbose_name': 'Observación de proceso',
                'verbose_name_plural': 'Observaciones de procesos',
                'ordering': ['etapa', 'ronda', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='solicitudvisita',
            name='pausado_por_proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_pausadas', to='a03Prop.procesocompra', verbose_name='Pausado por proceso'),
        ),
    ]
