# Generated by Django 6.0.6 on 2026-07-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a03Prop', '0007_solicitudvisita_pausado_procesocompra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo_cierre',
            field=models.CharField(blank=True, choices=[('vendida', 'Vendida'), ('arrendada', 'Arrendada')], max_length=20, null=True, verbose_name='Tipo de cierre'),
        ),
    ]
