# Generated by Django 6.0.6 on 2026-07-05 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a03Prop', '0008_propiedad_fecha_cierre_propiedad_tipo_cierre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='tipo_moneda',
            field=models.CharField(choices=[('PCL', 'CLP'), ('UF', 'UF'), ('USD', 'USD')], default='PCL', max_length=5, verbose_name='Tipo de moneda'),
        ),
        migrations.AlterField(
            model_name='propuestacompra',
            name='moneda',
            field=models.CharField(choices=[('PCL', 'CLP'), ('UF', 'UF'), ('USD', 'USD')], default='PCL', max_length=5, verbose_name='Moneda'),
        ),
        migrations.CreateModel(
            name='CierreEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio de venta/arriendo (nominal)')),
                ('moneda_original', models.CharField(choices=[('PCL', 'CLP'), ('UF', 'UF'), ('USD', 'USD')], default='PCL', max_length=5, verbose_name='Moneda original')),
                ('factor_uf_clp', models.DecimalField(blank=True, decimal_places=2, help_text='Valor de la UF en CLP a la fecha del cierre', max_digits=12, null=True, verbose_name='Valor UF → CLP')),
                ('factor_usd_clp', models.DecimalField(blank=True, decimal_places=2, help_text='Valor del USD en CLP a la fecha del cierre', max_digits=12, null=True, verbose_name='Valor USD → CLP')),
                ('pct_comision_vendedor', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Comisión vendedor')),
                ('pct_comision_comprador', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Comisión comprador')),
                ('comision_vendedor_presupuestada_clp', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Comisión vendedor presupuestada (CLP)')),
                ('comision_comprador_presupuestada_clp', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Comisión comprador presupuestada (CLP)')),
                ('comision_vendedor_recibida', models.DecimalField(blank=True, decimal_places=2, help_text='Valor real efectivamente recibido del vendedor', max_digits=15, null=True, verbose_name='Comisión vendedor RECIBIDA (CLP)')),
                ('comision_vendedor_por_recibir', models.DecimalField(blank=True, decimal_places=2, help_text='Saldo pendiente de recibir del vendedor', max_digits=15, null=True, verbose_name='Comisión vendedor POR RECIBIR (CLP)')),
                ('comision_comprador_recibida', models.DecimalField(blank=True, decimal_places=2, help_text='Valor real efectivamente recibido del comprador', max_digits=15, null=True, verbose_name='Comisión comprador RECIBIDA (CLP)')),
                ('comision_comprador_por_recibir', models.DecimalField(blank=True, decimal_places=2, help_text='Saldo pendiente de recibir del comprador', max_digits=15, null=True, verbose_name='Comisión comprador POR RECIBIR (CLP)')),
                ('plan_nombre', models.CharField(blank=True, max_length=50, verbose_name='Nombre del plan del corredor')),
                ('tasa_serca', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje que SERCA cobra al corredor (del plan)', max_digits=5, verbose_name='Tasa comisión SERCA (%)')),
                ('costo_publicacion_clp', models.DecimalField(blank=True, decimal_places=2, help_text='Costo que SERCA erogó por la publicación', max_digits=12, null=True, verbose_name='Costo de publicación (CLP)')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('perfeccionado', models.BooleanField(default=False, help_text='Indica si el corredor ya ajustó los valores reales', verbose_name='Perfeccionado')),
                ('fecha_cierre', models.DateTimeField(verbose_name='Fecha de cierre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corredor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres_economicos', to=settings.AUTH_USER_MODEL, verbose_name='Corredor responsable')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres_economicos', to='a03Prop.propiedad', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Cierre Económico',
                'verbose_name_plural': 'Cierres Económicos',
                'ordering': ['-anio', '-mes'],
            },
        ),
    ]
