# Generated by Django 6.0.6 on 2026-07-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a03Prop', '0009_alter_propiedad_tipo_moneda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corredorprop',
            name='corredor_puede_editar',
            field=models.BooleanField(default=True, help_text='El gerente/superadmin activa esto para que el corredor pueda editar los datos', verbose_name='Corredor puede editar propiedad'),
        ),
        migrations.AddField(
            model_name='corredorprop',
            name='dueno_puede_editar',
            field=models.BooleanField(default=True, help_text='El corredor activa esto para que el dueño pueda editar los datos', verbose_name='Dueño puede editar propiedad'),
        ),
    ]
