# Generated by Django 6.0.6 on 2026-07-18 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a03Prop', '0010_corredorprop_corredor_puede_editar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvisita',
            name='orden_visita_firmada',
            field=models.FileField(blank=True, null=True, upload_to='ordenes_visita_firmadas/', verbose_name='Orden de Visita Firmada (PDF)'),
        ),
        migrations.AddField(
            model_name='solicitudvisita',
            name='orden_visita_firmada_subida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_visita_firmadas_subidas', to=settings.AUTH_USER_MODEL, verbose_name='OV Firmada subida por'),
        ),
    ]
