# Generated by Django 6.0.6 on 2026-07-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a03Prop', '0011_add_orden_visita_firmada'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuestacompra',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Razón por la que el dueño/corredor rechazó esta propuesta', verbose_name='Motivo del rechazo'),
        ),
    ]
