# Generated by Django 6.0.6 on 2026-07-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a03Prop', '0012_add_motivo_rechazo_propuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvisita',
            name='contrato_aceptado_arrendador',
            field=models.BooleanField(default=False, verbose_name='Arrendador aceptó contrato'),
        ),
        migrations.AddField(
            model_name='solicitudvisita',
            name='contrato_aceptado_arrendador_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudvisita',
            name='contrato_aceptado_arrendatario',
            field=models.BooleanField(default=False, verbose_name='Arrendatario aceptó contrato'),
        ),
        migrations.AddField(
            model_name='solicitudvisita',
            name='contrato_aceptado_arrendatario_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudvisita',
            name='contrato_aceptado_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aceptado por ambos el'),
        ),
        migrations.AddField(
            model_name='solicitudvisita',
            name='contrato_arriendo_ronda',
            field=models.PositiveIntegerField(default=0, verbose_name='Ronda de revisión (contrato)'),
        ),
    ]
