# Generated by Django 5.2.5 on 2026-07-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a03Prop', '0013_solicitudvisita_contrato_aceptado_arrendador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvisita',
            name='notaria_aceptada_arrendador',
            field=models.BooleanField(default=False, verbose_name='Arrendador aceptó cita notarial'),
        ),
        migrations.AddField(
            model_name='solicitudvisita',
            name='notaria_aceptada_arrendador_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudvisita',
            name='notaria_aceptada_arrendatario',
            field=models.BooleanField(default=False, verbose_name='Arrendatario aceptó cita notarial'),
        ),
        migrations.AddField(
            model_name='solicitudvisita',
            name='notaria_aceptada_arrendatario_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudvisita',
            name='notaria_confirmada',
            field=models.BooleanField(default=False, verbose_name='Cita notarial confirmada (deprecated)'),
        ),
    ]
