# Generated by Django 5.2.5 on 2026-07-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a03Prop', '0014_add_notaria_aceptacion_campos'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesocompra',
            name='precio_venta_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio real de la compraventa (puede diferir del publicado)', max_digits=15, null=True, verbose_name='Precio venta final (rectificado en Promesa)'),
        ),
        migrations.AddField(
            model_name='procesocompra',
            name='tasa_serca',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se pre-puebla desde OG, editable por gerente', max_digits=5, null=True, verbose_name='Tasa SERCA (%)'),
        ),
        migrations.AddField(
            model_name='procesocompra',
            name='tipo_comision_comprador',
            field=models.CharField(blank=True, choices=[('porcentaje', 'Porcentaje'), ('fijo', 'Monto Fijo')], max_length=20, verbose_name='Tipo comisión comprador'),
        ),
        migrations.AddField(
            model_name='procesocompra',
            name='tipo_comision_vendedor',
            field=models.CharField(blank=True, choices=[('porcentaje', 'Porcentaje'), ('fijo', 'Monto Fijo')], max_length=20, verbose_name='Tipo comisión vendedor'),
        ),
        migrations.AddField(
            model_name='procesocompra',
            name='tipo_moneda_final',
            field=models.CharField(blank=True, choices=[('PCL', 'CLP'), ('UF', 'UF'), ('USD', 'USD')], max_length=5, verbose_name='Moneda final'),
        ),
        migrations.AddField(
            model_name='procesocompra',
            name='valor_comision_comprador',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor comisión comprador (% o monto fijo)'),
        ),
        migrations.AddField(
            model_name='procesocompra',
            name='valor_comision_vendedor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor comisión vendedor (% o monto fijo)'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='precio_referencia_og',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de venta o canon arriendo al momento de la OG', max_digits=15, null=True, verbose_name='Precio referencia desde OG'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='tasa_serca_og',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se pre-puebla desde el plan del corredor, editable', max_digits=5, null=True, verbose_name='Tasa SERCA desde OG (%)'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='tipo_comision_comprador_og',
            field=models.CharField(blank=True, choices=[('porcentaje', 'Porcentaje'), ('fijo', 'Monto Fijo')], max_length=20, verbose_name='Tipo comisión comprador (OG)'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='tipo_comision_vendedor_og',
            field=models.CharField(blank=True, choices=[('porcentaje', 'Porcentaje'), ('fijo', 'Monto Fijo')], max_length=20, verbose_name='Tipo comisión vendedor (OG)'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='valor_comision_comprador_og',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor comisión comprador (OG) - % o monto fijo'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='valor_comision_vendedor_og',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor comisión vendedor (OG) - % o monto fijo'),
        ),
    ]
