# Generated by Django 5.2.5 on 2026-07-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a03Prop', '0015_add_comision_campos_og_proceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvisita',
            name='canon_arriendo_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio real del arriendo (puede diferir del publicado)', max_digits=15, null=True, verbose_name='Canon arriendo final (rectificado en Contrato)'),
        ),
        migrations.AddField(
            model_name='solicitudvisita',
            name='tasa_serca_arriendo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se pre-puebla desde OG, editable', max_digits=5, null=True, verbose_name='Tasa SERCA arriendo (%)'),
        ),
        migrations.AddField(
            model_name='solicitudvisita',
            name='tipo_comision_arrendador',
            field=models.CharField(blank=True, choices=[('porcentaje', 'Porcentaje'), ('fijo', 'Monto Fijo')], max_length=20, verbose_name='Tipo comisión arrendador (dueño)'),
        ),
        migrations.AddField(
            model_name='solicitudvisita',
            name='tipo_comision_arrendatario',
            field=models.CharField(blank=True, choices=[('porcentaje', 'Porcentaje'), ('fijo', 'Monto Fijo')], max_length=20, verbose_name='Tipo comisión arrendatario (usuario)'),
        ),
        migrations.AddField(
            model_name='solicitudvisita',
            name='valor_comision_arrendador',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor comisión arrendador (% o monto fijo)'),
        ),
        migrations.AddField(
            model_name='solicitudvisita',
            name='valor_comision_arrendatario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor comisión arrendatario (% o monto fijo)'),
        ),
    ]
