# Generated by Django 6.0.6 on 2026-08-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a03Prop', '0016_add_comision_campos_arriendo'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigable para motores de búsqueda. Se genera automáticamente.', max_length=255, null=True, unique=True, verbose_name='Slug SEO'),
        ),
    ]
