# Generated by Django 6.0.6 on 2026-08-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a03Prop', '0019_regen_slugs_nombre_comuna'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviciosprop',
            options={'ordering': ['categoria', 'nombre'], 'verbose_name': 'Servicio de propiedad', 'verbose_name_plural': 'Servicios de propiedades'},
        ),
        migrations.AddField(
            model_name='serviciosprop',
            name='categoria',
            field=models.CharField(choices=[('entorno', 'Entorno y Ubicación'), ('equipamiento', 'Equipamiento e Instalaciones (Condominio / Edificio)'), ('interior', 'Características de la Propiedad (Interior)')], default='entorno', max_length=20, verbose_name='Categoría'),
        ),
    ]
