# Generated by Django 6.0.6 on 2026-10-03 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a03Prop', '0020_alter_serviciosprop_options_serviciosprop_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cierreeconomico',
            name='factor_uf_og',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='UF → CLP usada para las comisiones'),
        ),
        migrations.AddField(
            model_name='cierreeconomico',
            name='factor_usd_og',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='USD → CLP usada para las comisiones'),
        ),
        migrations.AddField(
            model_name='cierreeconomico',
            name='moneda_comision_comprador',
            field=models.CharField(choices=[('PCL', 'CLP'), ('UF', 'UF'), ('USD', 'USD')], default='PCL', max_length=5, verbose_name='Moneda de la comisión del comprador'),
        ),
        migrations.AddField(
            model_name='cierreeconomico',
            name='moneda_comision_vendedor',
            field=models.CharField(choices=[('PCL', 'CLP'), ('UF', 'UF'), ('USD', 'USD')], default='PCL', max_length=5, verbose_name='Moneda de la comisión del vendedor'),
        ),
        migrations.AddField(
            model_name='cierreeconomico',
            name='origen_comisiones',
            field=models.CharField(blank=True, choices=[('og', 'Orden de Gestión'), ('corredor_prop', 'Ficha del corredor'), ('manual', 'Carga manual')], help_text='De dónde salieron los valores presupuestados', max_length=20, verbose_name='Origen de las comisiones'),
        ),
        migrations.AddField(
            model_name='cierreeconomico',
            name='tipo_comision_comprador',
            field=models.CharField(blank=True, choices=[('porcentaje', 'Porcentaje del precio'), ('fijo', 'Monto fijo')], max_length=20, verbose_name='Tipo comisión comprador'),
        ),
        migrations.AddField(
            model_name='cierreeconomico',
            name='tipo_comision_vendedor',
            field=models.CharField(blank=True, choices=[('porcentaje', 'Porcentaje del precio'), ('fijo', 'Monto fijo')], max_length=20, verbose_name='Tipo comisión vendedor'),
        ),
        migrations.AddField(
            model_name='cierreeconomico',
            name='valor_comision_comprador_origen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Comisión comprador en origen (% o monto)'),
        ),
        migrations.AddField(
            model_name='cierreeconomico',
            name='valor_comision_vendedor_origen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Comisión vendedor en origen (% o monto)'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='en_representacion',
            field=models.BooleanField(default=False, verbose_name='Publicada en representación'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='propietario_celular',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono del propietario'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='propietario_dni',
            field=models.CharField(blank=True, max_length=20, verbose_name='RUT del propietario'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='propietario_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email del propietario'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='propietario_nombre',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del propietario'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades_representadas', to=settings.AUTH_USER_MODEL, verbose_name='Representante'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='aviso_abierto_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='El propietario abrió el aviso el'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='aviso_email_destino',
            field=models.EmailField(blank=True, help_text='Queda registrado por si el propietario reclama después', max_length=254, verbose_name='Email al que se envió el aviso'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='aviso_enviado_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aviso enviado al propietario el'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='aviso_token',
            field=models.CharField(blank=True, max_length=64, verbose_name='Token del enlace de objeción'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='factor_uf_og',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor UF → CLP usado en la OG'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='factor_usd_og',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor USD → CLP usado en la OG'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='fecha_tipo_cambio_og',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del tipo de cambio de la OG'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='mandato_archivo',
            field=models.FileField(blank=True, null=True, upload_to='mandatos/', verbose_name='Mandato firmado por el propietario'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='mandato_validado_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Mandato validado el'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='mandato_validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandatos_validados', to=settings.AUTH_USER_MODEL, verbose_name='Mandato validado por'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='moneda_comision_comprador_og',
            field=models.CharField(choices=[('PCL', 'CLP'), ('UF', 'UF'), ('USD', 'USD')], default='PCL', max_length=5, verbose_name='Moneda de la comisión del comprador'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='moneda_comision_vendedor_og',
            field=models.CharField(choices=[('PCL', 'CLP'), ('UF', 'UF'), ('USD', 'USD')], default='PCL', max_length=5, verbose_name='Moneda de la comisión del vendedor'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='moneda_referencia_og',
            field=models.CharField(choices=[('PCL', 'CLP'), ('UF', 'UF'), ('USD', 'USD')], default='PCL', max_length=5, verbose_name='Moneda del precio de referencia'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='objecion_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Objetada el'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='objecion_dias',
            field=models.PositiveSmallIntegerField(default=1, help_text='Mínimo 1, máximo 7. Lo fija el gerente al aprobar el pago', verbose_name='Días de plazo para objetar'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='objecion_hasta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Se puede publicar a partir de'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='objecion_motivo',
            field=models.TextField(blank=True, verbose_name='Motivo de la objeción'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='objetada',
            field=models.BooleanField(default=False, verbose_name='¿Objetada por el propietario?'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='og_aceptada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ogs_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='OG aprobada por'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='tasa_serca_plan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tasa SERCA del plan al momento de la OG'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='tipo_mandato',
            field=models.CharField(blank=True, choices=[('verbal', 'Verbal'), ('escrito', 'Escrito simple firmado'), ('notarial', 'Notarial / poder amplio')], max_length=20, verbose_name='Tipo de mandato'),
        ),
        migrations.AddField(
            model_name='solicitudpublicacion',
            name='tipo_publicante',
            field=models.CharField(choices=[('propietario', 'El propio propietario'), ('representante', 'Representante del propietario')], default='propietario', max_length=20, verbose_name='Quién publica'),
        ),
        migrations.AlterField(
            model_name='cierreeconomico',
            name='pct_comision_comprador',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sólo tiene sentido cuando el tipo es porcentaje', max_digits=5, null=True, verbose_name='% Comisión comprador'),
        ),
        migrations.AlterField(
            model_name='cierreeconomico',
            name='pct_comision_vendedor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sólo tiene sentido cuando el tipo es porcentaje', max_digits=5, null=True, verbose_name='% Comisión vendedor'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='dueno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades', to=settings.AUTH_USER_MODEL, verbose_name='Dueño (si tiene cuenta)'),
        ),
        migrations.AlterField(
            model_name='solicitudpublicacion',
            name='estado',
            field=models.CharField(choices=[('pago_revision', 'Pago en revisión'), ('pago_objetado', 'Pago objetado'), ('pago_aprobado', 'Pago aprobado'), ('esperando_corredor', 'Esperando asignación de corredor'), ('en_revision_corredor', 'En revisión del corredor'), ('og_pendiente', 'Orden de Gestión pendiente de aprobación'), ('og_aceptada', 'Orden de Gestión aprobada'), ('en_validacion', 'En validación final'), ('publicada', 'Publicada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada'), ('objetada', 'Objetada por el propietario')], default='pago_revision', max_length=30, verbose_name='Estado'),
        ),
    ]
