# Generated by Django 6.0.6 on 2026-06-14 01:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Comuna')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('imagen', models.ImageField(upload_to='funcionarios/', verbose_name='Imagen')),
                ('curriculo', models.TextField(verbose_name='Currículo/Biografía')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del plan')),
                ('tipo', models.CharField(choices=[('corredor', 'Corredor'), ('vendedor', 'Vendedor (Usuario Base)')], default='corredor', max_length=20, verbose_name='Tipo de plan')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('duracion_meses', models.IntegerField(default=1, verbose_name='Duración (meses)')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('max_propiedades_simultaneas', models.PositiveSmallIntegerField(default=5, verbose_name='Máx. propiedades simultáneas')),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=60.0, help_text='Porcentaje de comisión que recibe el corredor', max_digits=5, verbose_name='Comisión (%)')),
            ],
            options={
                'verbose_name': 'Plan de suscripción',
                'verbose_name_plural': 'Planes de suscripción',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('superadmin', 'Superadmin'), ('gerente', 'Gerente'), ('corredor', 'Corredor'), ('base', 'Usuario Base')], default='base', max_length=20, verbose_name='Rol')),
                ('dni', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RUT/DNI')),
                ('cel_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono celular')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/', verbose_name='Foto')),
                ('domicilio', models.CharField(blank=True, max_length=255, verbose_name='Domicilio')),
                ('curriculo', models.TextField(blank=True, verbose_name='Currículo')),
                ('email_confirmado', models.BooleanField(default=False, verbose_name='Email confirmado')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('valido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_validados', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a00seg.comuna', verbose_name='Comuna')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='a00seg.region', verbose_name='Región'),
        ),
        migrations.CreateModel(
            name='SolicitudCorredor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('dni', models.CharField(blank=True, max_length=20, verbose_name='RUT/DNI')),
                ('cel_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono celular')),
                ('domicilio', models.CharField(blank=True, max_length=255, verbose_name='Domicilio')),
                ('curriculo', models.TextField(blank=True, verbose_name='Currículo / Experiencia')),
                ('comprobante', models.ImageField(upload_to='comprobantes_corredor/', verbose_name='Comprobante de depósito')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_dialogo', 'En diálogo'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('observaciones_admin', models.TextField(blank=True, verbose_name='Observaciones del administrador')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revisión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de postulación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a00seg.comuna', verbose_name='Comuna')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a00seg.plansuscripcion', verbose_name='Plan seleccionado')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_corredor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario (si ya tenía cuenta)')),
            ],
            options={
                'verbose_name': 'Solicitud de corredor',
                'verbose_name_plural': 'Solicitudes de corredores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuscripcionCorredor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha de término')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('renovacion_avisada', models.BooleanField(default=False, verbose_name='Renovación avisada')),
                ('corredor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to=settings.AUTH_USER_MODEL, verbose_name='Corredor')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a00seg.plansuscripcion', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Suscripción de corredor',
                'verbose_name_plural': 'Suscripciones de corredores',
            },
        ),
        migrations.CreateModel(
            name='SuscripcionVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha de término')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('renovacion_avisada', models.BooleanField(default=False, verbose_name='Renovación avisada')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='a00seg.plansuscripcion', verbose_name='Plan')),
                ('vendedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion_vendedor', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Suscripción de vendedor',
                'verbose_name_plural': 'Suscripciones de vendedores',
            },
        ),
        migrations.CreateModel(
            name='AgendaCorredor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora fin')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('cupos_por_hora', models.PositiveSmallIntegerField(default=1, verbose_name='Cupos por hora')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('corredor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_visitas', to=settings.AUTH_USER_MODEL, verbose_name='Corredor')),
            ],
            options={
                'verbose_name': 'Agenda de corredor',
                'verbose_name_plural': 'Agendas de corredores',
                'ordering': ['corredor_id', 'fecha', 'hora_inicio'],
                'constraints': [models.UniqueConstraint(fields=('corredor', 'fecha', 'hora_inicio', 'hora_fin'), name='unique_agenda_corredor_bloque')],
            },
        ),
    ]
