# Generated by Django 6.0.6 on 2026-06-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a00seg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendacorredor',
            name='reservado',
            field=models.BooleanField(default=False, verbose_name='Reservado'),
        ),
    ]
