# Generated by Django 6.0.6 on 2026-08-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a00seg', '0002_agendacorredor_reservado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigable para landing pages por comuna. Se genera automáticamente.', max_length=255, null=True, unique=True, verbose_name='Slug SEO'),
        ),
    ]
