# Generated by Django 6.0.6 on 2026-08-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a00seg', '0004_populate_comuna_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuna',
            name='descripcion_seo',
            field=models.TextField(blank=True, help_text='Texto único que aparece al final de la landing page de esta comuna. Si está vacío se muestra un texto genérico. Escribe 2-3 frases que describan la comuna: conectividad, comercio, colegios, parques, etc.', verbose_name='Descripción SEO (landing page)'),
        ),
    ]
