# Generated by Django 6.0.6 on 2026-08-14 14:06

import cloudinary_storage.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a00seg', '0007_funcionario_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentogestion',
            name='archivo',
            field=models.FileField(help_text='PDF, Word, Excel, imágenes u otros formatos', storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='docs_gestion/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='documentogestion',
            name='subido_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_gestion_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
    ]
