# Generated by Django 6.0.6 on 2026-10-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a00seg', '0008_alter_documentogestion_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansuscripcion',
            name='max_publicaciones_mensual',
            field=models.PositiveSmallIntegerField(default=5, help_text='Cuántas publicaciones puede crear el corredor en un mes calendario, sean propias o en representación.', verbose_name='Máx. publicaciones por mes calendario'),
        ),
        migrations.AddField(
            model_name='plansuscripcion',
            name='permite_representacion',
            field=models.BooleanField(default=False, help_text='Habilita que un corredor publique propiedades de terceros.', verbose_name='Permite publicar en representación'),
        ),
        migrations.AlterField(
            model_name='plansuscripcion',
            name='comision_porcentaje',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Porcentaje de la comisión que recibe el corredor. SERCA cobra el complemento (100 - este valor). El valor por defecto es solo un punto de partida: ajústalo al crear cada plan.', max_digits=5, verbose_name='Comisión que recibe el corredor (%)'),
        ),
    ]
