# Generated by Django 6.0.6 on 2026-07-08 22:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la categoría')),
                ('icono', models.CharField(blank=True, max_length=50, verbose_name='Icono (emoji/clase CSS)')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden de aparición')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría de servicio',
                'verbose_name_plural': 'Categorías de servicios',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ServicioPublicitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del servicio')),
                ('descripcion', models.TextField(verbose_name='Descripción del servicio')),
                ('imagen', models.ImageField(upload_to='servicios/', verbose_name='Imagen del servicio')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio web del publicante')),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de contacto')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('tipo_plan', models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual')], max_length=10, verbose_name='Tipo de plan')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto pagado')),
                ('iva_incluido', models.BooleanField(default=True, verbose_name='IVA incluido en el monto')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('fecha_expiracion', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='activo', max_length=20, verbose_name='Estado')),
                ('renovacion_avisada', models.BooleanField(default=False, verbose_name='Renovación avisada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='a07serv.categoriaservicio', verbose_name='Categoría')),
                ('publicante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_publicitarios', to=settings.AUTH_USER_MODEL, verbose_name='Publicante (prestador)')),
            ],
            options={
                'verbose_name': 'Servicio publicitario',
                'verbose_name_plural': 'Servicios publicitarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PagoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('mensual', 'Mensual (CLP $4.200 + IVA)'), ('anual', 'Anual (CLP $39.800 + IVA)')], max_length=10, verbose_name='Tipo de pago')),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto base')),
                ('monto_iva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IVA (19%)')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto total')),
                ('comprobante', models.ImageField(upload_to='comprobantes_servicios/', verbose_name='Comprobante de pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('observaciones_admin', models.TextField(blank=True, verbose_name='Observaciones del admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pago')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('publicante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_servicios', to=settings.AUTH_USER_MODEL, verbose_name='Publicante')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_servicios_revisados', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='a07serv.serviciopublicitario', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Pago de servicio',
                'verbose_name_plural': 'Pagos de servicios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MensajeServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_remitente', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('email_remitente', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono_remitente', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('mensaje', models.TextField(verbose_name='Mensaje / Requerimiento')),
                ('is_leido', models.BooleanField(default=False, verbose_name='Leído por el publicante')),
                ('leido_at', models.DateTimeField(blank=True, null=True, verbose_name='Leído el')),
                ('respuesta', models.TextField(blank=True, verbose_name='Respuesta del publicante')),
                ('respondido_at', models.DateTimeField(blank=True, null=True, verbose_name='Respondido el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='a07serv.serviciopublicitario', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Mensaje de servicio',
                'verbose_name_plural': 'Mensajes de servicios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CasoExito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del caso')),
                ('descripcion', models.TextField(verbose_name='Descripción / Testimonio')),
                ('imagen_antes', models.ImageField(blank=True, null=True, upload_to='casos_exito/', verbose_name="Imagen 'Antes'")),
                ('imagen_despues', models.ImageField(blank=True, null=True, upload_to='casos_exito/', verbose_name="Imagen 'Después'")),
                ('cliente_nombre', models.CharField(max_length=255, verbose_name='Nombre del cliente')),
                ('cliente_testimonio', models.TextField(blank=True, verbose_name='Testimonio del cliente')),
                ('is_publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_exito', to='a07serv.serviciopublicitario', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Caso de éxito',
                'verbose_name_plural': 'Casos de éxito',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RatingServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mostrar', models.CharField(blank=True, max_length=100, verbose_name='Nombre a mostrar')),
                ('puntaje', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntaje (1-5)')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario (anónimo si no autenticado)')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='a07serv.serviciopublicitario', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Calificación de servicio',
                'verbose_name_plural': 'Calificaciones de servicios',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('servicio', 'usuario'), name='unique_rating_servicio_usuario')],
            },
        ),
    ]
