# Generated by Django 5.2.5 on 2026-07-17 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a03Prop', '0010_corredorprop_corredor_puede_editar_and_more'),
        ('a07serv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casoexito',
            name='propiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casos_exito', to='a03Prop.propiedad', verbose_name='Propiedad (opcional)'),
        ),
        migrations.AlterField(
            model_name='casoexito',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casos_exito', to='a07serv.serviciopublicitario', verbose_name='Servicio (opcional)'),
        ),
    ]
