# Generated by Django 6.0.6 on 2026-07-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a07serv', '0002_casoexito_propiedad_alter_casoexito_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPrecioServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_mensual', models.PositiveIntegerField(default=4200, verbose_name='Valor plan mensual (CLP)')),
                ('valor_anual', models.PositiveIntegerField(default=39800, verbose_name='Valor plan anual (CLP)')),
                ('iva', models.DecimalField(decimal_places=2, default=0.19, max_digits=4, verbose_name='IVA (decimal)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Configuración de precio de servicio',
                'verbose_name_plural': 'Configuraciones de precios de servicios',
            },
        ),
    ]
