# Generated by Django 6.0.6 on 2026-08-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a07serv', '0003_configuracionprecioservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciopublicitario',
            name='estado',
            field=models.CharField(choices=[('en_revision', 'En revisión'), ('objetado', 'Objetado'), ('activo', 'Activo'), ('pausado', 'Pausado'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='en_revision', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='serviciopublicitario',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, help_text='Se asigna cuando el gerente aprueba e inicia la publicación.', null=True, verbose_name='Fecha de expiración'),
        ),
    ]
