# Generated by Django 6.0.6 on 2026-08-02 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a07serv', '0004_alter_serviciopublicitario_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciopublicitario',
            name='observaciones_admin',
            field=models.TextField(blank=True, verbose_name='Observaciones / motivo de objeción'),
        ),
        migrations.AddField(
            model_name='serviciopublicitario',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_revisados', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
    ]
