# Generated by Django 6.0.6 on 2026-08-10 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a07serv', '0005_serviciopublicitario_observaciones_admin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeservicio',
            name='destinatario',
            field=models.ForeignKey(blank=True, help_text='Publicante del servicio que recibe el mensaje.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_servicios_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario (publicante)'),
        ),
        migrations.AddField(
            model_name='mensajeservicio',
            name='remitente',
            field=models.ForeignKey(blank=True, help_text='Usuario autenticado que envió el mensaje. Null si fue anónimo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_servicios_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Remitente (usuario autenticado)'),
        ),
        migrations.AddIndex(
            model_name='mensajeservicio',
            index=models.Index(fields=['servicio', 'remitente'], name='msg_serv_rem_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajeservicio',
            index=models.Index(fields=['servicio', 'email_remitente'], name='msg_serv_email_idx'),
        ),
    ]
